### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [tienan92it/PreworkCalculator#1]
Hi Tran An,

Thank you for your work hard, awesome !!! just one more step will make your Prework become the best. You missed README file content, could you please update README file based on content that we have provided. Ahhh don't forget to check checkboxes that you have done. Here is an example of README template https://github.com/mikenk2010/prework_react_native_readme/blob/master/README.md

Could you please update your application before 6PM - Mar 11 2017.

Have a nice weekend!
CoderSchool.vn

**Comment by tienan92it** [comment]
Hi CoderSchool, Thank for your remind. I have updated my README file content and still have been improving my code. I'll make a new submit once there are some new things.

Thank you,
An Tran
